version: '3.9'
services:
  web:
    image: 2757429/exadel
    ports:
      - "8080:80"
  java:
    image: jboss/wildfly
    ports:
      - "8090:80"
    depends_on:
      - "db"
    command: ["./wait-for-it.sh", "db:5432"]
  db:
    image: postgres
    ports:
      - "5432:5432"