version: '2'
services:
  web:
    image: ${ImgWEB}
    ports:
      - "${PortWEB}"
  java:
    container_name: myjava
    image: ${ImgJava}
    ports:
      - "${PortJava}"
    depends_on:
      - "db"
  db:
    container_name: mydb
    image: ${ImgDB}
    ports:
      - "${PortDB}"