version: '2'
services:
  web:
    image: 2757429/exadel
    ports:
      - "8075-8085:80"
  java:
    container_name: myjava
    image: milkyway/java-hello-world
    ports:
      - "8090:80"
    depends_on:
      - "db"
  db:
    container_name: mydb
    image: mongo
    ports:
      - "27019:27019"