---

- hosts: all
  become: true

  tasks:
    - name: insatll DOCKER
      yum:
        name: docker
        state: latest
    - name: start DOCKER
      service:
        name: docker
        state: started